AWSTemplateFormatVersion: 2010-09-09
Description: Create a VPC and an assumable role for cross account VPC peering.
Parameters:
  PrivateVPCIDCIDRRange:
    Description: The IP address range for your new Private VPC.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: ### put cidr range here
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  VpcId: 
    "Description" : VpcId of your existing Virtual Private Cloud (VPC)
    "Type" : "AWS::EC2::VPC::Id"
    "ConstraintDescription" : "must be the VPC Id of an existing Virtual Private Cloud."
  
Resources:
  PeeringRoute2:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref PrivateVPCIDCIDRRange ## the cidr of vpc to be peered with 
      RouteTableId: ### enter route table id 
      VpcPeeringConnectionId: !Ref vpcPeeringConnection
  PeeringRoute1:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref PrivateVPCIDCIDRRange #### the cidr of vpc to be peered with 
      RouteTableId: ### enter route table id
      VpcPeeringConnectionId: !Ref vpcPeeringConnection
    #Peering connection            
  vpcPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref VpcId     # requester vpc id
      PeerVpcId: ##  # accepter vpc id
      PeerOwnerId:     # accepter aws account id
      PeerRoleArn: arn:aws:iam::of the peering connection role              
Outputs:
  VPCPeeringConnectionId:
    Value: !Ref vpcPeeringConnection